version: 5.1.0
variant: default
logo: https://user-images.githubusercontent.com/7054676/56820277-0a54ac00-687e-11e9-9f34-f79089938638.png
head:
    favicon: https://user-images.githubusercontent.com/7054676/56820343-2fe1b580-687e-11e9-8f6f-778df3a8eafd.png
    manifest:
        name: 
        short_name: 
        start_url: 
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        主页: .
        文章: archives
        分类: categories
        标签: tags
        订阅: /atom.xml
        周报: weekly
        我的简历: resume
        关于我: about
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/Zheaoli
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/Zheaoli/manjusaka-blog
article:
    highlight:
        theme: github
        clipboard: true
        fold: unfolded
    readtime: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
comment:
    type: disqus
    shortname: manjusakablog
share:
    type: sharethis
    install_url: https://platform-api.sharethis.com/js/sharethis.js#property=62a60a35caa5c30019736818&product=inline-share-buttons
sidebar:
    left:
        sticky: true
    right:
        sticky: false
widgets:
    -
        type: profile
        position: left
        author: Manjusaka
        author_title: Stay simple && Stay Naive
        location: Beijing, China
        avatar: https://user-images.githubusercontent.com/7054676/56820343-2fe1b580-687e-11e9-8f6f-778df3a8eafd.png
        gravatar: 
        avatar_rounded: false
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/Zheaoli
            Twitter:
                icon: fab fa-twitter
                url: https://twitter.com/Manjusaka_Lee
            Telegram:
                icon: fab fa-telegram
                url: https://t.me/ManjusakaL
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: left
        type: links
        links:
            捕蛇者说: https://pythonhunter.org/
            laike9m's Blog: https://laike9m.com/
            Adam Wen's Blog: https://darkof.me/
            卡瓦邦噶: https://www.kawabangga.com/
            千里冰封: http://ice1000.org/
            leiysky: https://leiysky.github.io/
            漩涡的博客: https://xuanwo.io/
            写代码的猴子: http://jaeger.itscoder.com
            你好，耳先生: https://www.kilerd.me/
            homura: https://homura.live/
            extremej: http://extremej.itscoder.com
            imxie: http://imxie.itscoder.com
            Jing's Blog: http://www.iamlj.com
            ymkiux: https://ymkiux.github.io
            Irony: https://suyan.moe/
    -
        position: left
        type: categories
    -
        position: right
        type: archives
    -
        position: right
        type: tags
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 56ca085ae4b8a4667f041cdd04856321
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    gallery: true
    google_analytics:
        tracking_id: UA-154407994-1
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
